//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCuniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_has_student
    {
        public Nullable<int> courseID { get; set; }
        public Nullable<int> students_registrationNumber { get; set; }
        public Nullable<int> grade { get; set; }
        public int id { get; set; }
    
        public virtual course course { get; set; }
        public virtual student student { get; set; }
    }
}
