//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCuniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class secretary
    {
        public int phonenumber { get; set; }
        public string name { get; set; }
        public string surename { get; set; }
        public string department { get; set; }
        public string USERS_USERNAME { get; set; }
    
        public virtual user user { get; set; }
    }
}
